INSERT INTO `soal` (`soal_id`, `soal_teks`, `kode_lomba`) VALUES
    (1, 'Berikut ini mana yang bukan jenis akun yang memerlukan penyesuaian pada akhir periode akuntansi?', 'video-5'),
    (2, 'Pada saat akhir tahun, perusahaan belum membayar beban gaji pegawainya. Tipe jurnal penyesuaian mana yang dibuat pada akhir tahun?', 'video-5'),
    (3, 'Saldo perlengakapan (supplies) pada neraca percobaan (trial balance) menunjukkan nilai Rp10 juta. Namun, pada saat dihitung pada akhir tahun, ternyata nilai perlengkapan menunjukkan angka Rp7,5 juta. Penyesuaian yang dilakukan adalah:', 'video-5'),
    (4, 'Di bawah ini, akun aset mana yang tidak memerlukan depresiasi pada akhir tahun?', 'video-5'),
    (5, 'PT ABC melakukan pekerjaan jasa konstruksi. Pada akhir tahun, PT ABC belum mendapatkan pembayaran atas jasanya. Atas kejadian tersebut, jurnal penyesuaian apa yang harus dibuat oleh PT ABC?', 'video-5'),
    (6, 'PT ABC, membayar asuransi peralatan untuk 1 tahun pada 1 Agustus 2020 sebesar Rp6 juta. Pada akhir tahun 2020, berapa saldo asuransi di bayar dimuka?', 'video-5'),
    (7, 'Di bawah ini, alasan utama peralatan perlu disesuaikan pada akhir tahun adalah', 'video-5'),
    (8, 'Pada 1 Juli 2020, PT ABC membeli Gedung senilai Rp120 juta. Gedung tersebut akan digunakan untuk Gudang persediaan dagang. Diperkirakan, Gedung akan memberikan manfaat selama 10 tahun. Berapa beban depresiasi yang perlu dicatat oleh PT ABC di akhir tahun 2020?', 'video-5'),
    (9, 'PT ABC membayar gaji pegawai hariannya setiap senin untuk gaji hari senin-sabtu minggu sebelumya. Gaji yang dibayar perusahaan ke pegawai tersebut setiap hari adalah Rp1 juta. Mereka bekerja dari hari Senin sampai Sabtu. Tanggal 31 Desember adalah hari Rabu. Bagaimana jurnal penyesuaian yang dibuat oleh PT ABC?', 'video-5'),
    (10, 'PT ABC menerima pembayaran sewa Gedung dari pelanggan pada 1 November 2020 sebesar Rp12 juta untuk jangka waktu 12 bulan dan dicatat pertama kali sebagai pendapatan sewa diterima dimuka. Bagaimana jurnal penyesuaian yang harus dibuat oleh PT ABC pada 31 Desember 2020?', 'video-5'),
    (11, 'Di bawah ini mana yang bukan merupakan bagian dari laporan keuangan?', 'video-6'),
    (12, 'Di bawah ini mana yang merupakan akun temporer/nominal?', 'video-6'),
    (13, 'Laporan keuangan yang menyajikan akun-akun real disebut dengan:', 'video-6'),
    (14, 'Manakah akun di bawah ini yang termasuk dalam aset lancar?', 'video-6'),
    (15, 'Cash yang berasal dari penjualan Gedung akan dicatat pada...', 'video-6'),
    (16, 'Akun manakah yang akan mengurangi saldo capital (ekuitas) perusahaan?', 'video-6'),
    (17, 'Jurnal yang dibuat di akhir tahun yang digunakan untuk membuat akun nominal bersaldo nol disebut dengan...', 'video-6'),
    (18, 'Pembayaran gaji pegawai akan dilaporkan pada...', 'video-6'),
    (19, 'Di bawah ini adalah laporan keuangan yang menyajikan saldo akun selama periode akuntansi tertentu, kecuali...', 'video-6'),
    (20, 'Yang termasuk dalam utang jangka Panjang adalah..', 'video-6'),
    (21, 'Hal-hal yang membedakan perusahaan dagang dengan perusahaan jasa adalah', 'video-7'),
    (22, 'Yang bukan merupakan bagian dari siklus operasi perusahaan dagang adalah:', 'video-7'),
    (23, 'Akun di bawah ini yang membedakan antara perusahaan dagang dengan perusahaan jasa, kecuali:', 'video-7'),
    (24, 'Pada saat terjadi penjualan barang dangan secara kredit dengan syarat 2/10, n/30, dan pembeli membayar utang tersebut pada hari ke-5 setelah transaksi, maka..', 'video-7'),
    (25, 'System pencatatan persediaan barang dagang yang hanya dapat mengetahui nilai persediaan akhir dengan cara dilakukan penghitungan fisik disebut dengan..', 'video-7'),
    (26, 'Apabila diketahui nilai pembelian total adalah Rp100 juta, diskon pembelian Rp5 juta, retur pembelian Rp10 juta dan biaya angkut yang terjadi adalah Rp 7 juta, maka berapa nilai persediaan yang dibeli?', 'video-7'),
    (27, 'Apabila diketahui saldo awal tahun persediaan adalah Rp50 juta, pembelian bersih Rp100 juta, dan saldo akhir tahun persediaan Rp75 juta, maka berapa harga pokok penjualannya?', 'video-7'),
    (28, 'Pada saat PT ABC membeli persediaan barang dengan dengan syarat pengantaran adalah FOB Shipping point, maka hak milik barang dagang akan berpindah tangan saat...', 'video-7'),
    (29, 'Pada saat PT ABC membeli persediaan barang dagang dengan syarat pengantaran adalah FOB destination point, maka biaya angkut ditanggung oleh...', 'video-7'),
    (30, 'Apabila diketahui net sales PT ABC adalah Rp100 juta, harga pokok penjualan Rp55 juta, beban administrasinya Rp 10 juta, dan biaya penjualannya adalah Rp 15 juta. Maka berapa laba kotornya?', 'video-7'),
    (31, 'Definisi akuntansi yang paling tepat adalah', 'video-1'),
    (32, 'Definisi akuntansi manajemen yang paling tepat adalah', 'video-1'),
    (33, 'Pengertian konsep entitas usaha yang paling tepat adalah', 'video-1'),
    (34, 'Pemilik usaha “Jasa Akuntansi Akurat” membeli sofa  di Toko Makmur untuk digunakan di rumah (pribadi).  Pernyataan yang tepat adalah', 'video-1'),
    (35, 'Potong Rambut Rapi membeli alat cukur di Toko Maju.  Siapa yang mencatat transaksi tersebut?', 'video-1'),
    (36, 'Pengertian konsep harga perolehan yang tepat adalah', 'video-1'),
    (37, 'Penjual menawarkan harga sebuat produk Rp1,5 juta.  Pembeli mengecek di internet harganya antara Rp1,4 juta sampai dengan 1,6 juta.  Pembeli menawar dengan harga Rp1,3 juta. Akhirnya penjual dan pembeli sepakat di harga Rp1,4 juta.  Harga yang dicatat oleh pembeli adalah', 'video-1'),
    (38, 'Pengertian konsep objektivitas yang paling tepat adalah', 'video-1'),
    (39, 'Harga sebuah model baju yang tercantum di label Rp99.000,00; harga di internet Rp80.000,00 – 120.000,00; harga yang tercantum di nota penjualan Rp90.000,00.  Nilai transaksi yang dicatat sebesar', 'video-1'),
    (40, 'Pengertian konsep unit pengukuran yang paling tepat adalah', 'video-1'),
    (41, 'Okto setor uang untuk memulai usaha baru yang diberi nama “Jasa Akuntansi Akurat”.  Pernyataan yang paling tepat adalah', 'video-2'),
    (42, 'Jasa Akuntansi Akurat membeli tanah seharga Rp50 juta, di bayar tahun depan.  Pernyataan yang paling tepat adalah', 'video-2'),
    (43, 'Jasa Akuntansi Akurat membeli perlengkapan seharga Rp1 juta di bayar tunai.  Pernyataan yang paling tepat adalah', 'video-2'),
    (44, 'Jasa Akuntansi Akurat menerima pembayaran atas jasa yang diberikan.  Pernyataan yang paling tepat adalah', 'video-2'),
    (45, 'Jasa Akuntansi Akurat membayar beban upah dan beban sewa.  Pernyataan yang paling tepat adalah', 'video-2'),
    (46, 'Jasa Akuntansi Akurat melunasi utang usaha.  Pernyataan yang paling tepat adalah', 'video-2'),
    (47, 'Pada akhir bulan, Jasa Akuntansi Akurat menghitung perlengkapan yang masih ada ditangan nilainya Rp500.000,00 dan perlengkapan yang terpakai Rp500.000,00.  Pernyataan yang paling tepat adalah', 'video-2'),
    (48, 'Okto mengambil uang usaha untuk keperluan pribadi.  Pernyataan yang paling tepat adalah', 'video-2'),
    (49, 'Jasa Akuntansi Akurat membeli tanah seharga Rp10 juta, di bayar tunai.  Pernyataan yang paling tepat adalah', 'video-2'),
    (50, 'Okto setor uang dan perlengkapan kantor untuk menambah modal usaha.  Pernyataan yang paling tepat adalah', 'video-2'),
    (51, 'Pernyataan terkait saldo normal yang paling tepat adalah', 'video-3'),
    (52, 'Pernyataan terkait DEBIT dan KREDIT yang paling tepat adalah', 'video-3'),
    (53, 'Okto setor uang Rp5 juta untuk memulai usaha baru yang diberi nama “Jasa Akuntansi Akurat”.  Jurnal yang paling tepat adalah', 'video-3'),
    (54, 'Jasa Akuntansi Akurat membeli tanah seharga Rp50 juta, di bayar tahun depan.  Jurnal yang paling tepat adalah', 'video-3'),
    (55, 'Jasa Akuntansi Akurat membeli perlengkapan seharga Rp1 juta di bayar tunai.  Jurnal yang paling tepat adalah', 'video-3'),
    (56, 'Jasa Akuntansi Akurat menerima pembayaran atas jasa yang diberikan Rp3 juta.  Jurnal yang paling tepat adalah', 'video-3'),
    (57, 'Jasa Akuntansi Akurat membayar beban upah Rp1 juta dan beban sewa Rp1 juta.  Jurnal yang paling tepat adalah', 'video-3'),
    (58, 'Jasa Akuntansi Akurat melunasi utang usaha Rp1 juta.  Jurnal yang paling tepat adalah', 'video-3'),
    (59, 'Pada akhir bulan, Jasa Akuntansi Akurat menghitung perlengkapan yang masih ada ditangan nilainya Rp500.000,00 dan perlengkapan yang terpakai Rp500.000,00.  Jurnal yang paling tepat adalah', 'video-3'),
    (60, 'Okto mengambil uang usaha untuk keperluan pribadi Rp 1 juta.  Jurnal yang paling tepat adalah', 'video-3'),
    (61, 'Tanggal 1 Oktober Jasa Akuntansi Akurat membayar sewa ruko Rp12 juta untuk masa 1 tahun.   Jurnal yang dibuat adalah', 'video-4'),
    (62, 'Tanggal 1 Oktober Jasa Akuntansi Akurat membayar premi asuransi untuk bulan Oktober Rp100.000,00.   Jurnal yang dibuat adalah', 'video-4'),
    (63, 'Tanggal 1 Oktober sebuah toko menyewa sebagian tanah dan membayar Rp200.000,00 untuk masa sewa 1 bulan.  Jurnal yang dibuat adalah', 'video-4'),
    (64, 'Tanggal 1 Oktober sebuah toko menyewa sebagian tanah dan membayar Rp1,2 juta untuk masa sewa 6 bulan.  Jurnal yang dibuat adalah', 'video-4'),
    (65, 'Membeli peralatan Rp8 juta, setengahnya dibayar tunai, setengahnya dibayar tahun depan. Jurnal yang tepat adalah', 'video-4'),
    (66, 'Menyelesaikan jasa pesanan pelanggan dengan nilai Rp4 juta dan akan dibayar bulan depan. Jurnal yang paling tepat adalah', 'video-4'),
    (67, 'Menerima pelunasan piutang Rp2 juta dari pelanggan. Jurnal yang paling tepat adalah', 'video-4'),
    (68, 'Pernyataan yang paling tepat terkait posting adalah', 'video-4'),
    (69, 'Pernyataan yang paling tepat terkait buku besar (Account) adalah', 'video-4'),
    (70, 'Pernyataan yang paling tepat terkait Undjusted Trial Balance adalah', 'video-4');


INSERT INTO soal VALUES
    (201,'Soal PG AccSMA Segmen 1 Nomor 1','AccSMA' ),
    (202,'Soal PG AccSMA Segmen 1 Nomor 2','AccSMA'),
    (203,'Soal PG AccSMA Segmen 1 Nomor 3','AccSMA'),
    (204,'Soal PG AccSMA Segmen 1 Nomor 4','AccSMA'),
    (205,'Soal PG AccSMA Segmen 1 Nomor 5','AccSMA'),
    (206,'Soal PG AccSMA Segmen 1 Nomor 6','AccSMA'),
    (207,'Soal PG AccSMA Segmen 1 Nomor 7','AccSMA'),
    (208,'Soal PG AccSMA Segmen 1 Nomor 8','AccSMA'),
    (209,'Soal PG AccSMA Segmen 1 Nomor 9','AccSMA'),
    (210,'Soal PG AccSMA Segmen 1 Nomor 10','AccSMA'),
    (211,'Soal PG AccSMA Segmen 1 Nomor 11','AccSMA'),
    (212,'Soal PG AccSMA Segmen 1 Nomor 12','AccSMA'),
    (213,'Soal PG AccSMA Segmen 1 Nomor 13','AccSMA'),
    (214,'Soal PG AccSMA Segmen 1 Nomor 14','AccSMA'),
    (215,'Soal PG AccSMA Segmen 1 Nomor 15','AccSMA'),
    (216,'Soal PG AccSMA Segmen 1 Nomor 16','AccSMA'),
    (217,'Soal PG AccSMA Segmen 1 Nomor 17','AccSMA'),
    (218,'Soal PG AccSMA Segmen 1 Nomor 18','AccSMA'),
    (219,'Soal PG AccSMA Segmen 1 Nomor 19','AccSMA'),
    (220,'Soal PG AccSMA Segmen 1 Nomor 20','AccSMA'),
    (221,'Soal PG AccSMA Segmen 1 Nomor 21','AccSMA'),
    (222,'Soal PG AccSMA Segmen 1 Nomor 22','AccSMA'),
    (223,'Soal PG AccSMA Segmen 1 Nomor 23','AccSMA'),
    (224,'Soal PG AccSMA Segmen 1 Nomor 24','AccSMA'),
    (225,'Soal PG AccSMA Segmen 1 Nomor 25','AccSMA'),
    (226,'Soal PG AccSMA Segmen 1 Nomor 26','AccSMA'),
    (227,'Soal PG AccSMA Segmen 1 Nomor 27','AccSMA'),
    (228,'Soal PG AccSMA Segmen 1 Nomor 28','AccSMA'),
    (229,'Soal PG AccSMA Segmen 1 Nomor 29','AccSMA'),
    (230,'Soal PG AccSMA Segmen 1 Nomor 30','AccSMA'),
    (231,'Soal PG AccSMA Segmen 1 Nomor 31','AccSMA'),
    (232,'Soal PG AccSMA Segmen 1 Nomor 32','AccSMA'),
    (233,'Soal PG AccSMA Segmen 1 Nomor 33','AccSMA'),
    (234,'Soal PG AccSMA Segmen 1 Nomor 34','AccSMA'),
    (235,'Soal PG AccSMA Segmen 1 Nomor 35','AccSMA'),
    (236,'Soal PG AccSMA Segmen 1 Nomor 36','AccSMA'),
    (237,'Soal PG AccSMA Segmen 1 Nomor 37','AccSMA'),
    (238,'Soal PG AccSMA Segmen 1 Nomor 38','AccSMA'),
    (239,'Soal PG AccSMA Segmen 1 Nomor 39','AccSMA'),
    (240,'Soal PG AccSMA Segmen 1 Nomor 40','AccSMA'),
    (241,'Soal BS AccSMA Segmen 1 Nomor 41','AccSMA'),
    (242,'Soal BS AccSMA Segmen 1 Nomor 42','AccSMA'),
    (243,'Soal BS AccSMA Segmen 1 Nomor 43','AccSMA'),
    (244,'Soal BS AccSMA Segmen 1 Nomor 44','AccSMA'),
    (245,'Soal BS AccSMA Segmen 1 Nomor 45','AccSMA'),
    (246,'Soal BS AccSMA Segmen 1 Nomor 46','AccSMA'),
    (247,'Soal BS AccSMA Segmen 1 Nomor 47','AccSMA'),
    (248,'Soal BS AccSMA Segmen 1 Nomor 48','AccSMA'),
    (249,'Soal BS AccSMA Segmen 1 Nomor 49','AccSMA'),
    (250,'Soal BS AccSMA Segmen 1 Nomor 50','AccSMA'),
    (251,'Soal PG AccSMA Segmen 2 Nomor 1','AccSMA'),
    (252,'Soal PG AccSMA Segmen 2 Nomor 2','AccSMA'),
    (253,'Soal PG AccSMA Segmen 2 Nomor 3','AccSMA'),
    (254,'Soal PG AccSMA Segmen 2 Nomor 4','AccSMA'),
    (255,'Soal PG AccSMA Segmen 2 Nomor 5','AccSMA'),
    (256,'Soal PG AccSMA Segmen 2 Nomor 6','AccSMA'),
    (257,'Soal PG AccSMA Segmen 2 Nomor 7','AccSMA'),
    (258,'Soal PG AccSMA Segmen 2 Nomor 8','AccSMA'),
    (259,'Soal PG AccSMA Segmen 2 Nomor 9','AccSMA'),
    (260,'Soal PG AccSMA Segmen 2 Nomor 10','AccSMA'),
    (261,'Soal PG AccSMA Segmen 2 Nomor 11','AccSMA'),
    (262,'Soal PG AccSMA Segmen 2 Nomor 12','AccSMA'),
    (263,'Soal PG AccSMA Segmen 2 Nomor 13','AccSMA'),
    (264,'Soal PG AccSMA Segmen 2 Nomor 14','AccSMA'),
    (265,'Soal PG AccSMA Segmen 2 Nomor 15','AccSMA'),
    (266,'Soal PG AccSMA Segmen 2 Nomor 16','AccSMA'),
    (267,'Soal PG AccSMA Segmen 2 Nomor 17','AccSMA'),
    (268,'Soal PG AccSMA Segmen 2 Nomor 18','AccSMA'),
    (269,'Soal PG AccSMA Segmen 2 Nomor 19','AccSMA'),
    (270,'Soal PG AccSMA Segmen 2 Nomor 20','AccSMA'),
    (271,'Soal PG AccSMA Segmen 2 Nomor 21','AccSMA'),
    (272,'Soal PG AccSMA Segmen 2 Nomor 22','AccSMA'),
    (273,'Soal PG AccSMA Segmen 2 Nomor 23','AccSMA'),
    (274,'Soal PG AccSMA Segmen 2 Nomor 24','AccSMA'),
    (275,'Soal PG AccSMA Segmen 2 Nomor 25','AccSMA'),
    (276,'Soal PG AccSMA Segmen 2 Nomor 26','AccSMA'),
    (277,'Soal PG AccSMA Segmen 2 Nomor 27','AccSMA'),
    (278,'Soal PG AccSMA Segmen 2 Nomor 28','AccSMA'),
    (279,'Soal PG AccSMA Segmen 2 Nomor 29','AccSMA'),
    (280,'Soal PG AccSMA Segmen 2 Nomor 30','AccSMA'),
    (281,'Soal PG AccSMA Segmen 2 Nomor 31','AccSMA'),
    (282,'Soal PG AccSMA Segmen 2 Nomor 32','AccSMA'),
    (283,'Soal PG AccSMA Segmen 2 Nomor 33','AccSMA'),
    (284,'Soal PG AccSMA Segmen 2 Nomor 34','AccSMA'),
    (285,'Soal PG AccSMA Segmen 2 Nomor 35','AccSMA'),
    (286,'Soal PG AccSMA Segmen 2 Nomor 36','AccSMA'),
    (287,'Soal PG AccSMA Segmen 2 Nomor 37','AccSMA'),
    (288,'Soal PG AccSMA Segmen 2 Nomor 38','AccSMA'),
    (289,'Soal PG AccSMA Segmen 2 Nomor 39','AccSMA'),
    (290,'Soal PG AccSMA Segmen 2 Nomor 40','AccSMA'),
    (291,'Soal BS AccSMA Segmen 2 Nomor 41','AccSMA'),
    (292,'Soal BS AccSMA Segmen 2 Nomor 42','AccSMA'),
    (293,'Soal BS AccSMA Segmen 2 Nomor 43','AccSMA'),
    (294,'Soal BS AccSMA Segmen 2 Nomor 44','AccSMA'),
    (295,'Soal BS AccSMA Segmen 2 Nomor 45','AccSMA'),
    (296,'Soal BS AccSMA Segmen 2 Nomor 46','AccSMA'),
    (297,'Soal BS AccSMA Segmen 2 Nomor 47','AccSMA'),
    (298,'Soal BS AccSMA Segmen 2 Nomor 48','AccSMA'),
    (299,'Soal BS AccSMA Segmen 2 Nomor 49','AccSMA'),
    (300,'Soal BS AccSMA Segmen 2 Nomor 50','AccSMA'),
    (301,'Soal PG AccSMA Segmen 3 Nomor 1','AccSMA'),
    (302,'Soal PG AccSMA Segmen 3 Nomor 2','AccSMA'),
    (303,'Soal PG AccSMA Segmen 3 Nomor 3','AccSMA'),
    (304,'Soal PG AccSMA Segmen 3 Nomor 4','AccSMA'),
    (305,'Soal PG AccSMA Segmen 3 Nomor 5','AccSMA'),
    (306,'Soal PG AccSMA Segmen 3 Nomor 6','AccSMA'),
    (307,'Soal PG AccSMA Segmen 3 Nomor 7','AccSMA'),
    (308,'Soal PG AccSMA Segmen 3 Nomor 8','AccSMA'),
    (309,'Soal PG AccSMA Segmen 3 Nomor 9','AccSMA'),
    (310,'Soal PG AccSMA Segmen 3 Nomor 10','AccSMA'),
    (311,'Soal PG AccSMA Segmen 3 Nomor 11','AccSMA'),
    (312,'Soal PG AccSMA Segmen 3 Nomor 12','AccSMA'),
    (313,'Soal PG AccSMA Segmen 3 Nomor 13','AccSMA'),
    (314,'Soal PG AccSMA Segmen 3 Nomor 14','AccSMA'),
    (315,'Soal PG AccSMA Segmen 3 Nomor 15','AccSMA'),
    (316,'Soal PG AccSMA Segmen 3 Nomor 16','AccSMA'),
    (317,'Soal PG AccSMA Segmen 3 Nomor 17','AccSMA'),
    (318,'Soal PG AccSMA Segmen 3 Nomor 18','AccSMA'),
    (319,'Soal PG AccSMA Segmen 3 Nomor 19','AccSMA'),
    (320,'Soal PG AccSMA Segmen 3 Nomor 20','AccSMA'),
    (321,'Soal PG AccSMA Segmen 3 Nomor 21','AccSMA'),
    (322,'Soal PG AccSMA Segmen 3 Nomor 22','AccSMA'),
    (323,'Soal PG AccSMA Segmen 3 Nomor 23','AccSMA'),
    (324,'Soal PG AccSMA Segmen 3 Nomor 24','AccSMA'),
    (325,'Soal PG AccSMA Segmen 3 Nomor 25','AccSMA'),
    (326,'Soal PG AccSMA Segmen 3 Nomor 26','AccSMA'),
    (327,'Soal PG AccSMA Segmen 3 Nomor 27','AccSMA'),
    (328,'Soal PG AccSMA Segmen 3 Nomor 28','AccSMA'),
    (329,'Soal PG AccSMA Segmen 3 Nomor 29','AccSMA'),
    (330,'Soal PG AccSMA Segmen 3 Nomor 30','AccSMA'),
    (331,'Soal PG AccSMA Segmen 3 Nomor 31','AccSMA'),
    (332,'Soal PG AccSMA Segmen 3 Nomor 32','AccSMA'),
    (333,'Soal PG AccSMA Segmen 3 Nomor 33','AccSMA'),
    (334,'Soal PG AccSMA Segmen 3 Nomor 34','AccSMA'),
    (335,'Soal PG AccSMA Segmen 3 Nomor 35','AccSMA'),
    (336,'Soal PG AccSMA Segmen 3 Nomor 36','AccSMA'),
    (337,'Soal PG AccSMA Segmen 3 Nomor 37','AccSMA'),
    (338,'Soal PG AccSMA Segmen 3 Nomor 38','AccSMA'),
    (339,'Soal PG AccSMA Segmen 3 Nomor 39','AccSMA'),
    (340,'Soal PG AccSMA Segmen 3 Nomor 40','AccSMA'),
    (341,'Soal BS AccSMA Segmen 3 Nomor 41','AccSMA'),
    (342,'Soal BS AccSMA Segmen 3 Nomor 42','AccSMA'),
    (343,'Soal BS AccSMA Segmen 3 Nomor 43','AccSMA'),
    (344,'Soal BS AccSMA Segmen 3 Nomor 44','AccSMA'),
    (345,'Soal BS AccSMA Segmen 3 Nomor 45','AccSMA'),
    (346,'Soal BS AccSMA Segmen 3 Nomor 46','AccSMA'),
    (347,'Soal BS AccSMA Segmen 3 Nomor 47','AccSMA'),
    (348,'Soal BS AccSMA Segmen 3 Nomor 48','AccSMA'),
    (349,'Soal BS AccSMA Segmen 3 Nomor 49','AccSMA'),
    (350,'Soal BS AccSMA Segmen 3 Nomor 50','AccSMA'),
    (351,'Soal PG AccUniv Segmen 1 Nomor 1','AccUniv'),
    (352,'Soal PG AccUniv Segmen 1 Nomor 2','AccUniv'),
    (353,'Soal PG AccUniv Segmen 1 Nomor 3','AccUniv'),
    (354,'Soal PG AccUniv Segmen 1 Nomor 4','AccUniv'),
    (355,'Soal PG AccUniv Segmen 1 Nomor 5','AccUniv'),
    (356,'Soal PG AccUniv Segmen 1 Nomor 6','AccUniv'),
    (357,'Soal PG AccUniv Segmen 1 Nomor 7','AccUniv'),
    (358,'Soal PG AccUniv Segmen 1 Nomor 8','AccUniv'),
    (359,'Soal PG AccUniv Segmen 1 Nomor 9','AccUniv'),
    (360,'Soal PG AccUniv Segmen 1 Nomor 10','AccUniv'),
    (361,'Soal PG AccUniv Segmen 1 Nomor 11','AccUniv'),
    (362,'Soal PG AccUniv Segmen 1 Nomor 12','AccUniv'),
    (363,'Soal PG AccUniv Segmen 1 Nomor 13','AccUniv'),
    (364,'Soal PG AccUniv Segmen 1 Nomor 14','AccUniv'),
    (365,'Soal PG AccUniv Segmen 1 Nomor 15','AccUniv'),
    (366,'Soal PG AccUniv Segmen 1 Nomor 16','AccUniv'),
    (367,'Soal PG AccUniv Segmen 1 Nomor 17','AccUniv'),
    (368,'Soal PG AccUniv Segmen 1 Nomor 18','AccUniv'),
    (369,'Soal PG AccUniv Segmen 1 Nomor 19','AccUniv'),
    (370,'Soal PG AccUniv Segmen 1 Nomor 20','AccUniv'),
    (371,'Soal PG AccUniv Segmen 1 Nomor 21','AccUniv'),
    (372,'Soal PG AccUniv Segmen 1 Nomor 22','AccUniv'),
    (373,'Soal PG AccUniv Segmen 1 Nomor 23','AccUniv'),
    (374,'Soal PG AccUniv Segmen 1 Nomor 24','AccUniv'),
    (375,'Soal PG AccUniv Segmen 1 Nomor 25','AccUniv'),
    (376,'Soal PG AccUniv Segmen 1 Nomor 26','AccUniv'),
    (377,'Soal PG AccUniv Segmen 1 Nomor 27','AccUniv'),
    (378,'Soal PG AccUniv Segmen 1 Nomor 28','AccUniv'),
    (379,'Soal PG AccUniv Segmen 1 Nomor 29','AccUniv'),
    (380,'Soal PG AccUniv Segmen 1 Nomor 30','AccUniv'),
    (381,'Soal PG AccUniv Segmen 1 Nomor 31','AccUniv'),
    (382,'Soal PG AccUniv Segmen 1 Nomor 32','AccUniv'),
    (383,'Soal PG AccUniv Segmen 1 Nomor 33','AccUniv'),
    (384,'Soal PG AccUniv Segmen 1 Nomor 34','AccUniv'),
    (385,'Soal PG AccUniv Segmen 1 Nomor 35','AccUniv'),
    (386,'Soal PG AccUniv Segmen 1 Nomor 36','AccUniv'),
    (387,'Soal PG AccUniv Segmen 1 Nomor 37','AccUniv'),
    (388,'Soal PG AccUniv Segmen 1 Nomor 38','AccUniv'),
    (389,'Soal PG AccUniv Segmen 1 Nomor 39','AccUniv'),
    (390,'Soal PG AccUniv Segmen 1 Nomor 40','AccUniv'),
    (391,'Soal BS AccUniv Segmen 1 Nomor 41','AccUniv'),
    (392,'Soal BS AccUniv Segmen 1 Nomor 42','AccUniv'),
    (393,'Soal BS AccUniv Segmen 1 Nomor 43','AccUniv'),
    (394,'Soal BS AccUniv Segmen 1 Nomor 44','AccUniv'),
    (395,'Soal BS AccUniv Segmen 1 Nomor 45','AccUniv'),
    (396,'Soal BS AccUniv Segmen 1 Nomor 46','AccUniv'),
    (397,'Soal BS AccUniv Segmen 1 Nomor 47','AccUniv'),
    (398,'Soal BS AccUniv Segmen 1 Nomor 48','AccUniv'),
    (399,'Soal BS AccUniv Segmen 1 Nomor 49','AccUniv'),
    (400,'Soal BS AccUniv Segmen 1 Nomor 50','AccUniv'),
    (401,'Soal PG AccUniv Segmen 2 Nomor 1','AccUniv'),
    (402,'Soal PG AccUniv Segmen 2 Nomor 2','AccUniv'),
    (403,'Soal PG AccUniv Segmen 2 Nomor 3','AccUniv'),
    (404,'Soal PG AccUniv Segmen 2 Nomor 4','AccUniv'),
    (405,'Soal PG AccUniv Segmen 2 Nomor 5','AccUniv'),
    (406,'Soal PG AccUniv Segmen 2 Nomor 6','AccUniv'),
    (407,'Soal PG AccUniv Segmen 2 Nomor 7','AccUniv'),
    (408,'Soal PG AccUniv Segmen 2 Nomor 8','AccUniv'),
    (409,'Soal PG AccUniv Segmen 2 Nomor 9','AccUniv'),
    (410,'Soal PG AccUniv Segmen 2 Nomor 10','AccUniv'),
    (411,'Soal PG AccUniv Segmen 2 Nomor 11','AccUniv'),
    (412,'Soal PG AccUniv Segmen 2 Nomor 12','AccUniv'),
    (413,'Soal PG AccUniv Segmen 2 Nomor 13','AccUniv'),
    (414,'Soal PG AccUniv Segmen 2 Nomor 14','AccUniv'),
    (415,'Soal PG AccUniv Segmen 2 Nomor 15','AccUniv'),
    (416,'Soal PG AccUniv Segmen 2 Nomor 16','AccUniv'),
    (417,'Soal PG AccUniv Segmen 2 Nomor 17','AccUniv'),
    (418,'Soal PG AccUniv Segmen 2 Nomor 18','AccUniv'),
    (419,'Soal PG AccUniv Segmen 2 Nomor 19','AccUniv'),
    (420,'Soal PG AccUniv Segmen 2 Nomor 20','AccUniv'),
    (421,'Soal PG AccUniv Segmen 2 Nomor 21','AccUniv'),
    (422,'Soal PG AccUniv Segmen 2 Nomor 22','AccUniv'),
    (423,'Soal PG AccUniv Segmen 2 Nomor 23','AccUniv'),
    (424,'Soal PG AccUniv Segmen 2 Nomor 24','AccUniv'),
    (425,'Soal PG AccUniv Segmen 2 Nomor 25','AccUniv'),
    (426,'Soal PG AccUniv Segmen 2 Nomor 26','AccUniv'),
    (427,'Soal PG AccUniv Segmen 2 Nomor 27','AccUniv'),
    (428,'Soal PG AccUniv Segmen 2 Nomor 28','AccUniv'),
    (429,'Soal PG AccUniv Segmen 2 Nomor 29','AccUniv'),
    (430,'Soal PG AccUniv Segmen 2 Nomor 30','AccUniv'),
    (431,'Soal PG AccUniv Segmen 2 Nomor 31','AccUniv'),
    (432,'Soal PG AccUniv Segmen 2 Nomor 32','AccUniv'),
    (433,'Soal PG AccUniv Segmen 2 Nomor 33','AccUniv'),
    (434,'Soal PG AccUniv Segmen 2 Nomor 34','AccUniv'),
    (435,'Soal PG AccUniv Segmen 2 Nomor 35','AccUniv'),
    (436,'Soal PG AccUniv Segmen 2 Nomor 36','AccUniv'),
    (437,'Soal PG AccUniv Segmen 2 Nomor 37','AccUniv'),
    (438,'Soal PG AccUniv Segmen 2 Nomor 38','AccUniv'),
    (439,'Soal PG AccUniv Segmen 2 Nomor 39','AccUniv'),
    (440,'Soal PG AccUniv Segmen 2 Nomor 40','AccUniv'),
    (441,'Soal BS AccUniv Segmen 2 Nomor 41','AccUniv'),
    (442,'Soal BS AccUniv Segmen 2 Nomor 42','AccUniv'),
    (443,'Soal BS AccUniv Segmen 2 Nomor 43','AccUniv'),
    (444,'Soal BS AccUniv Segmen 2 Nomor 44','AccUniv'),
    (445,'Soal BS AccUniv Segmen 2 Nomor 45','AccUniv'),
    (446,'Soal BS AccUniv Segmen 2 Nomor 46','AccUniv'),
    (447,'Soal BS AccUniv Segmen 2 Nomor 47','AccUniv'),
    (448,'Soal BS AccUniv Segmen 2 Nomor 48','AccUniv'),
    (449,'Soal BS AccUniv Segmen 2 Nomor 49','AccUniv'),
    (450,'Soal BS AccUniv Segmen 2 Nomor 50','AccUniv'),
    (451,'Soal PG AccUniv Segmen 3 Nomor 1','AccUniv'),
    (452,'Soal PG AccUniv Segmen 3 Nomor 2','AccUniv'),
    (453,'Soal PG AccUniv Segmen 3 Nomor 3','AccUniv'),
    (454,'Soal PG AccUniv Segmen 3 Nomor 4','AccUniv'),
    (455,'Soal PG AccUniv Segmen 3 Nomor 5','AccUniv'),
    (456,'Soal PG AccUniv Segmen 3 Nomor 6','AccUniv'),
    (457,'Soal PG AccUniv Segmen 3 Nomor 7','AccUniv'),
    (458,'Soal PG AccUniv Segmen 3 Nomor 8','AccUniv'),
    (459,'Soal PG AccUniv Segmen 3 Nomor 9','AccUniv'),
    (460,'Soal PG AccUniv Segmen 3 Nomor 10','AccUniv'),
    (461,'Soal PG AccUniv Segmen 3 Nomor 11','AccUniv'),
    (462,'Soal PG AccUniv Segmen 3 Nomor 12','AccUniv'),
    (463,'Soal PG AccUniv Segmen 3 Nomor 13','AccUniv'),
    (464,'Soal PG AccUniv Segmen 3 Nomor 14','AccUniv'),
    (465,'Soal PG AccUniv Segmen 3 Nomor 15','AccUniv'),
    (466,'Soal PG AccUniv Segmen 3 Nomor 16','AccUniv'),
    (467,'Soal PG AccUniv Segmen 3 Nomor 17','AccUniv'),
    (468,'Soal PG AccUniv Segmen 3 Nomor 18','AccUniv'),
    (469,'Soal PG AccUniv Segmen 3 Nomor 19','AccUniv'),
    (470,'Soal PG AccUniv Segmen 3 Nomor 20','AccUniv'),
    (471,'Soal PG AccUniv Segmen 3 Nomor 21','AccUniv'),
    (472,'Soal PG AccUniv Segmen 3 Nomor 22','AccUniv'),
    (473,'Soal PG AccUniv Segmen 3 Nomor 23','AccUniv'),
    (474,'Soal PG AccUniv Segmen 3 Nomor 24','AccUniv'),
    (475,'Soal PG AccUniv Segmen 3 Nomor 25','AccUniv'),
    (476,'Soal PG AccUniv Segmen 3 Nomor 26','AccUniv'),
    (477,'Soal PG AccUniv Segmen 3 Nomor 27','AccUniv'),
    (478,'Soal PG AccUniv Segmen 3 Nomor 28','AccUniv'),
    (479,'Soal PG AccUniv Segmen 3 Nomor 29','AccUniv'),
    (480,'Soal PG AccUniv Segmen 3 Nomor 30','AccUniv'),
    (481,'Soal PG AccUniv Segmen 3 Nomor 31','AccUniv'),
    (482,'Soal PG AccUniv Segmen 3 Nomor 32','AccUniv'),
    (483,'Soal PG AccUniv Segmen 3 Nomor 33','AccUniv'),
    (484,'Soal PG AccUniv Segmen 3 Nomor 34','AccUniv'),
    (485,'Soal PG AccUniv Segmen 3 Nomor 35','AccUniv'),
    (486,'Soal PG AccUniv Segmen 3 Nomor 36','AccUniv'),
    (487,'Soal PG AccUniv Segmen 3 Nomor 37','AccUniv'),
    (488,'Soal PG AccUniv Segmen 3 Nomor 38','AccUniv'),
    (489,'Soal PG AccUniv Segmen 3 Nomor 39','AccUniv'),
    (490,'Soal PG AccUniv Segmen 3 Nomor 40','AccUniv'),
    (491,'Soal BS AccUniv Segmen 3 Nomor 41','AccUniv'),
    (492,'Soal BS AccUniv Segmen 3 Nomor 42','AccUniv'),
    (493,'Soal BS AccUniv Segmen 3 Nomor 43','AccUniv'),
    (494,'Soal BS AccUniv Segmen 3 Nomor 44','AccUniv'),
    (495,'Soal BS AccUniv Segmen 3 Nomor 45','AccUniv'),
    (496,'Soal BS AccUniv Segmen 3 Nomor 46','AccUniv'),
    (497,'Soal BS AccUniv Segmen 3 Nomor 47','AccUniv'),
    (498,'Soal BS AccUniv Segmen 3 Nomor 48','AccUniv'),
    (499,'Soal BS AccUniv Segmen 3 Nomor 49','AccUniv'),
    (500,'Soal BS AccUniv Segmen 3 Nomor 50','AccUniv');